// This file was a generated file that was accidentally committed to the source tree.
// It has been cleared to resolve a "duplicate class" error during build.
// The DaggerLauncherAppComponent class is generated by Dagger/KSP in the build/generated directory.
